
target 'AVPlayerMesh' do
  platform :ios, '11.0'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'LumenMeshSDK'

  # Pods for AVPlayerMesh
  #pod 'LumenMeshSDK'
end

target 'AVPlayerMeshTV' do
  platform :tvos, '13.0'

  use_frameworks!
  pod 'LumenMeshSDK'
end
