source 'https://cdn.cocoapods.org/'
inhibit_all_warnings!
use_frameworks!

def streamrootPod
  pod 'LumenOrchestratorSDK'
end

target 'AVPlayerCDNLoadBalancer' do
  platform :ios, '11.0'
  streamrootPod
end

target 'AVPlayerCDNLoadBalancerTV' do
  platform :tvos, '11.0'
  streamrootPod
end
