source 'https://cdn.cocoapods.org/'
inhibit_all_warnings!
use_frameworks!

def streamrootPod
  pod 'CTLOrchestratorSDK'
end

target 'AVPlayerOrchestrator' do
  platform :ios, '10.0'
  streamrootPod
end

target 'AVPlayerOrchestratorTV' do
  platform :tvos, '10.0'
  streamrootPod
end
