# Uncomment the next line to define a global platform for your project
source 'https://cdn.cocoapods.org/'
platform :ios, '10.0'
inhibit_all_warnings!

def streamrootPod
  pod 'CTLOrchestratorSDK'
end

target 'AVPlayerOrchestrator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  streamrootPod
end